
  List<String> messages = [
  "Képes vagy rá!",
  "Csak te és én :)",
  "Nyugodj meg, attól megnyugszol",
  "Kezd összeálni :)",
  "A legjob vagy! ;)",
  "Little pig, little pig, let in me!",
  "Say my name! ",
  "Ahol árnyék van, ott fény is!",
  "NEM VAGYOK BUZI!!",
  "Sötétbe is fényes vagy",
  "Never gonna give you up",
  "Én Svájc vagyok",
  "Nekem lehet jó!",
  "Mesélek a bornak",
  "Meséld el mégegyszer",
  "Sweet Caroline",
  "Good times never seem so good",
  "Ember most jövök ki a templomból",
  "NA én olyat nem játszok!!",
  "Kell egy kis bulika! :D",
  "VAN EGY SZÁL CIGID?",
  "Nyugi! :)",
  "Aki nem bírja minek iszik? Igaaz Máté?",
  "Ha ideges vagy, csak nyugodj le.",
  "Holnap én már nem jövök be",
  "Go Haza",
  "holnaptol tappenzen vok cs",
  "holnaptol igazolatlan",
  "igy van"
];
